"""remove is_urgent column

Revision ID: 49f80c164eac
Revises: 9114afbd4bb9
Create Date: 2025-04-23 11:28:50.046270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f80c164eac'
down_revision: Union[str, None] = '9114afbd4bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_urgent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_urgent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
